{% set name = "apache-airflow-providers-airbyte" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_airbyte-{{ version }}.tar.gz
  sha256: 516b448fcebc8215fac808b053f7088983f279eb13db633558b28969b08d4bc1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - airbyte-api >=0.52.0
    - apache-airflow-providers-http
    - apache-airflow >=2.8.0

test:
  imports:
    - airflow.providers.airbyte
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-airbyte for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/airbyte/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-airbyte/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
